'use client';
import Link from 'next/link';
import {useCallback,useEffect,useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowUpRight,ArrowRight,Target,Check,Clock,ChevronRight,ExternalLink,RotateCcw,Wallet,Plus,Film} from 'lucide-react';
import {baseSpec,defaultRanges,rangeLabel,score,validateSpec,type Round,type Prediction,type Specification} from '@/lib/domain';
import {browserPractice,browserLeague,browserPost,applyLive} from '@/lib/browser-practice';
import WalletControl from './wallet-control';
import PoolRehearsal from './pool-rehearsal';
import MovieStakes from './movie-stakes';
import MoviePoolDirectory from './movie-pool-directory';

type View='feed'|'round'|'result'|'predictions'|'league'|'creator'|'pools'|'pool-rehearsal';
type LeagueData={rounds:Round[];predictions:Prediction[];receipts:{hash:string;state:string}[];profile:{name:string;watchAddress?:string};leaderboard:{name:string;points:number;correct:number;resolved:number}[];draft:string;serverTime:number};
type Proof={contract:string;roundId:string;transactions:Record<string,string>;record?:Omit<Round,'id'|'title'|'year'|'description'|'artwork'>;pending?:boolean;reason?:string};
const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0}).format(n);
const date=(n:number)=>new Date(n*1000).toLocaleString('en-GB',{timeZone:'UTC',day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit'})+' UTC';
const passageText=(text:string)=>text.replaceAll('&nbsp;',' ');
async function post(body:unknown){if(browserPractice)return browserPost(body as Record<string,unknown>);const response=await fetch('/api/league',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??'Could not save. Try again.');return result;}
async function livePost(body:unknown){const response=await fetch('/api/live',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.error??'Protocol access failed. Try again.');if(browserPractice)applyLive(body as Record<string,unknown>,result);return result;}
async function walletClient(){
  const provider=(window as unknown as {ethereum?:{request:(args:{method:string;params?:unknown[]})=>Promise<unknown>}}).ethereum;
  if(!provider)throw new Error('Install or enable MetaMask to connect to StudioNet. The GenLayer wallet plugin is required.');
  const accounts=await provider.request({method:'eth_requestAccounts'}) as string[];
  if(!accounts[0]||!/^0x[a-fA-F0-9]{40}$/.test(accounts[0]))throw new Error('No wallet account was selected. Open your wallet and try again.');
  const [{createClient},{studionet}]=await Promise.all([import('genlayer-js'),import('genlayer-js/chains')]);
  const client=createClient({chain:studionet,account:accounts[0] as `0x${string}`,provider:provider as never});
  await client.connect('studionet');await livePost({action:'watch',address:accounts[0]});window.dispatchEvent(new CustomEvent('bullseye:wallet-connected',{detail:accounts[0]}));return client;
}
function Art({variant,title}:{variant:string;title:string}){return <div className={'film-art '+variant} role="img" aria-label={'Original Bullseye typographic artwork for '+title}><span className="art-letter" aria-hidden="true">{title.charAt(0)}</span><div className="art-title">{title}</div><span className="art-note">BULLSEYE ORIGINAL / TYPE STUDY</span><span className="art-ring" aria-hidden="true"/></div>;}
function Rules({round}:{round:Round}){return <details className="disclosure"><summary>How this round settles <Plus size={18}/></summary><div className="rules-body"><dl><dt>Event</dt><dd>{round.spec.event}</dd><dt>What counts</dt><dd>{round.spec.metric}. United States and Canada; USD dollars, scale 1. Exact published integer; no rounding.</dd><dt>Source</dt><dd><a href={round.spec.source_url} target="_blank" rel="noreferrer">The Numbers film page <ExternalLink size={14}/></a></dd><dt>Ranges</dt><dd>Lower boundaries included, upper boundaries excluded. The last range includes all larger values.</dd><dt>Timing</dt><dd>{round.spec.mode==='historical'&&!round.protocol?'Historical practice can be played at any time. Release weekend: '+round.spec.event.split(', ').at(-1)+'.':<>Entries close {date(round.spec.entry_deadline)}. Observation begins {date(round.spec.observation_time)}. Resolve by {date(round.spec.resolution_deadline)}.</>}</dd><dt>Corrections</dt><dd>The first successful consensus observation wins; later publisher corrections are ignored. No alternative source or administrator-entered result.</dd><dt>Missing evidence</dt><dd>Keep pending until the fixed deadline, then void. Void and unresolved rounds do not count toward accuracy.</dd><dt>Points</dt><dd>100 for the correct range, zero otherwise. An optional exact number inside your range adds up to 100 more: full marks for the exact figure, nothing once you’re 25% away. {round.spec.mode!=='competitive'?'This round is excluded from competitive rankings.':'Only finalized successful entries and adjudication count.'}</dd></dl></div></details>;}
function EvidencePanel({round}:{round:Round}){const e=round.evidence;if(!e)return <p className="notice">Evidence is pending. No winner or points have been assigned.</p>;return <section className="evidence"><h2>A number you can check.</h2><p>The published opening-weekend figure is matched to this round’s frozen metric, then code finds the containing range.</p><blockquote>{passageText(e.extracted_passage)}</blockquote><div className="source-line"><span>{e.provenance}</span><a href={e.approved_capture_url} target="_blank" rel="noreferrer">Inspect source <ArrowUpRight size={16}/></a></div><details className="disclosure"><summary>Evidence & technical record <Plus size={18}/></summary><dl className="technical"><dt>Original source</dt><dd>{e.original_source}</dd><dt>Approved capture</dt><dd>{e.approved_capture_url}</dd><dt>Observed</dt><dd>{date(e.capture_timestamp)}</dd><dt>Publication timestamp</dt><dd>{e.publication_timestamp?date(e.publication_timestamp):'Not supplied by the source; not inferred.'}</dd><dt>Normalized integer</dt><dd>{e.normalized_value} USD dollars</dd><dt>Exact retained passage</dt><dd>{e.extracted_passage}</dd><dt>Content hash</dt><dd><code>{e.content_hash}</code><p>{e.hash_scope}. A hash establishes integrity, not factual truth.</p></dd><dt>Specification hash</dt><dd><code>{e.specification_hash}</code></dd><dt>Adjudication transaction</dt><dd>{e.adjudication_transaction?<code>{e.adjudication_transaction}</code>:'No protocol transaction for this local practice result.'}</dd><dt>Capture policy</dt><dd>Live publisher pages can change. The protocol record describes validator retrieval; local historical practice uses the retained published passage without a protocol adjudication. No permanent full-page capture is claimed.</dd></dl></details></section>;}

export default function LeagueApp({view,roundId}:{view:View;roundId?:string}){
  const router=useRouter();const [data,setData]=useState<LeagueData|null>(null);const [proof,setProof]=useState<Proof|null>(null);
  const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [selected,setSelected]=useState<number|null>(null);const [guess,setGuess]=useState('');const [filter,setFilter]=useState('all');const [now,setNow]=useState(0);const [liveStatus,setLiveStatus]=useState('');
  const refresh=useCallback(async()=>{const [league,network]=await Promise.all([fetch('/api/league',{cache:'no-store'}),fetch('/api/protocol',{cache:'no-store'})]);if(!league.ok)throw new Error('The league could not load. Try again.');const result:LeagueData=browserPractice?browserLeague():await league.json();setData(result);setNow(result.serverTime);setProof(await network.json());},[]);
  useEffect(()=>{let active=true;Promise.resolve().then(()=>refresh()).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[refresh]);
  useEffect(()=>{if(!data)return;const timer=setInterval(()=>setNow(value=>value+1),1000);return()=>clearInterval(timer);},[data]);
  const round=data?.rounds.find(r=>r.id===roundId);const prediction=data?.predictions.find(p=>p.roundId===roundId);
  useEffect(()=>{if(!round||round.spec.mode!=='synthetic'||round.status==='resolved'||round.status==='void')return;const timer=setInterval(()=>refresh().catch(e=>setError(e.message)),2000);return()=>clearInterval(timer);},[round,refresh]);
  async function rehearse(){setBusy(true);setError('');try{const r:Round=await post({action:'rehearse'});router.push('/rounds/'+r.id);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  const guessValue=()=>{const n=Number(guess.replace(/[$,\s]/g,''));return guess.trim()!==''&&Number.isSafeInteger(n)&&n>0?n:0;};
  async function confirm(){if(!round||selected===null)return;setBusy(true);setError('');try{await post({action:'predict',roundId:round.id,range:selected,guess:guessValue()});await refresh();router.push('/rounds/'+round.id+'/result');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function syncLive(){setBusy(true);setError('');try{await livePost({action:'sync'});await refresh();setLiveStatus('Finalized protocol state refreshed.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function checkReceipt(hash:string){setBusy(true);setError('');try{await livePost({action:'receipt',hash});await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function protocolAction(method:string){if(!round?.protocol)return;setBusy(true);setError('');try{
    const client=await walletClient();
    const hash=await client.writeContract({address:round.protocol.contract as `0x${string}`,functionName:method==='predict'&&guessValue()?'predict_exact':method,args:method==='predict'?(guessValue()?[round.id,selected!,guessValue()]:[round.id,selected!]):[round.id],value:0n});
    localStorage.setItem('bullseye_live_receipt',JSON.stringify({hash,roundId:round.id,state:'submitted'}));
    await livePost({action:'receipt',hash});setLiveStatus('Submitted. Awaiting successful protocol finalization. Refresh protocol state to confirm.');await refresh();
  }catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <><a className="skip" href="#main">Skip to content</a><header className="header"><Link href="/" className="brand" aria-label="Bullseye home"><Target strokeWidth={2.3}/><span>BULLSEYE<span className="brand-dot">.</span></span></Link><nav aria-label="Main navigation"><Link href="/" aria-current={view==='feed'?'page':undefined}>Rounds</Link><Link href="/predictions" aria-current={view==='predictions'?'page':undefined}>My predictions</Link><Link href="/league" aria-current={view==='league'?'page':undefined}>The league</Link><Link href="/pools" aria-current={view==='pools'?'page':undefined}>GEN pools</Link><Link className="create-link" href="/create"><Plus size={17}/> Create a round</Link></nav><WalletControl connect={async()=>{await walletClient();await refresh();}}/></header>
  <main id="main" className="main">{error&&<div className="error" role="alert">{error}<button onClick={()=>{setError('');refresh().catch(e=>setError(e.message));}}>Retry loading</button></div>}
  {!data&&!error?<div className="loading" role="status"><Target/> Loading the programme…</div>:null}
  {data&&view==='feed'&&<><section className="hero"><div><h1>BIG SCREEN.<br/><span>BETTER CALLS.</span></h1><p>Know your opening weekends? Pick a range.<br className="desktop-break"/> Put your film instincts on the record.</p><div className="hero-actions"><Link href="/rounds/barbie-practice" className="button primary">Make your first call <ArrowUpRight size={19}/></Link><span>GEN pools and free points practice.</span></div></div><div className="hero-target" aria-hidden="true"><div/><div/><div/><span>CALL IT.<br/>CHECK IT.</span></div></section>
  <div className="principles"><span><Target size={17}/> One range. One call.</span><span><Check size={17}/> Right range = 100 · exact number up to +100</span><span><Film size={17}/> Real results. Visible evidence.</span></div>
  <section className="programme"><div className="section-heading"><h2>On the programme</h2><div className="filters" aria-label="Filter rounds">{[['all','All rounds'],['historical','Practice'],['synthetic','Rehearsals']].map(([value,label])=><button key={value} className={filter===value?'active':''} aria-pressed={filter===value} onClick={()=>setFilter(value)}>{label}</button>)}</div></div>
  {data.rounds.filter(r=>filter==='all'||r.spec.mode===filter).map(r=><article className="programme-row" key={r.id}><Link className="art-link" href={'/rounds/'+r.id}><Art variant={r.artwork} title={r.title}/></Link><div className="round-copy"><div className="round-meta"><span className={'tag '+r.spec.mode}>{r.spec.mode==='competitive'?'Live league round':r.spec.mode==='historical'?'Historical practice':'Synthetic rehearsal'}</span><span>{r.year} / Domestic opening weekend</span></div><h3><Link href={'/rounds/'+r.id}>{r.title}</Link></h3><p>{r.description}</p><div className="mini-ranges">{r.spec.ranges.map((range,i)=><span key={i}>{rangeLabel(range)}</span>)}</div><div className="round-bottom"><span><Clock size={15}/>{r.spec.mode==='historical'&&!r.protocol?'Play anytime · outside rankings':r.status==='resolved'?'Result ready':date(r.spec.entry_deadline)}</span><Link className="text-action" href={'/rounds/'+r.id}>{r.protocol&&r.status==='resolved'?'Inspect result':['barbie-practice','oppenheimer-practice','dune-two-practice'].includes(r.id)?'Stake GEN':'Choose your range'} <ArrowUpRight size={18}/></Link></div></div></article>)}
  {data.rounds.filter(r=>filter==='all'||r.spec.mode===filter).length===0&&<div className="empty"><h3>No rehearsals yet.</h3><p>Take the complete flow for a ten-second test drive.</p><button className="button primary" disabled={busy} onClick={rehearse}>Start a rehearsal <ArrowRight size={17}/></button></div>}
  <div className="rehearsal-strip"><div><h3>The whole flow. Ten seconds.</h3><p>An invented film, a synthetic result, and a repeatable rehearsal. No ranking points.</p></div><button className="button secondary" disabled={busy} onClick={rehearse}>{busy?'Starting…':'Run a rehearsal'}<RotateCcw size={17}/></button></div><div className="live-toolbar"><button className="text-action" disabled={busy} onClick={syncLive}>Refresh protocol rounds <RotateCcw size={15}/></button><span role="status">{liveStatus||'Live participation uses your own wallet; no relay or operator custody.'}</span></div></section><NetworkProof proof={proof}/></>}
  {data&&(view==='round'||view==='result')&&(!round?<div className="empty"><h1>Round not found.</h1><p>This rehearsal may belong to another guest session.</p><Link href="/">Return to rounds</Link></div>:<><Link className="back" href="/">All rounds <ChevronRight size={15}/> {round.title}</Link><div className="round-layout"><aside><Art variant={round.artwork} title={round.title}/><p className="art-caption">Original Bullseye artwork.<br/>Film titles identify the event.</p></aside><section className="round-main"><div className="round-meta"><span className={'tag '+round.spec.mode}>{round.spec.mode==='historical'?'Historical practice':'Synthetic rehearsal'}</span><span>{round.spec.mode==='competitive'?'Free league points':'Outside competitive rankings'}</span></div><h1>{round.title}<span className="year">{round.year==='SYNTHETIC'?' / Rehearsal':' / '+round.year}</span></h1><p className="question">Where did its domestic opening weekend land?</p><p className="muted">United States + Canada · USD · {round.spec.mode==='synthetic'?'Invented film and evidence':round.spec.event.split(', ').at(-1)}</p>
  {['barbie-practice','oppenheimer-practice','dune-two-practice'].includes(round.id)&&<><MovieStakes key={round.id} round={round} connect={walletClient}/><h2 className="free-practice-heading">Free points practice</h2></>}
  {round.spec.mode==='synthetic'&&round.status!=='resolved'&&<p className="notice" role="status">{now<round.spec.entry_deadline?`Entries close in ${Math.max(0,round.spec.entry_deadline-now)} seconds.`:'Entries closed. Waiting for the synthetic observation.'}</p>}
  {prediction?<div className="confirmed"><Check size={22}/><div><strong>Your call is on the record.</strong><p>{rangeLabel(round.spec.ranges[prediction.range])} · {prediction.kind==='protocol'?'Protocol finalized':'Practice confirmed'}</p></div></div>:round.protocol&&round.status!=='open'?<p className="notice">This protocol round is {round.status}. Entries are closed.</p>:<><fieldset className="picker"><legend>Choose your range</legend>{round.spec.ranges.map((range,i)=><label className={selected===i?'range-option selected':'range-option'} key={i}><input type="radio" name="range" checked={selected===i} onChange={()=>setSelected(i)} disabled={busy||((round.spec.mode==='synthetic'||!!round.protocol)&&now>=round.spec.entry_deadline)}/><span>{rangeLabel(range)}</span><span className="range-mark" aria-hidden="true">{selected===i?<Check size={17}/>:null}</span></label>)}</fieldset><label className="exact-guess"><span>Exact number <em>(optional bonus)</em></span><input inputMode="numeric" placeholder="e.g. 162,000,000" value={guess} onChange={e=>setGuess(e.target.value)} disabled={busy}/><small>Inside your range. Up to 100 extra points: full marks for the exact figure, nothing once you’re 25% away.</small></label><p className="small">One call per round. You can’t change it after confirming.</p><button className="button primary full" disabled={selected===null||busy||((round.spec.mode==='synthetic'||!!round.protocol)&&now>=round.spec.entry_deadline)} onClick={()=>round.protocol?protocolAction('predict'):confirm()}>{busy?'Saving your call…':round.protocol?'Submit prediction with wallet':'Confirm practice prediction'}<ArrowRight size={19}/></button><p className="small">{round.protocol?'Your wallet signs directly on StudioNet. No operator holds your keys. A submitted transaction is pending until finalized execution succeeds.':'Guest practice is saved to this browser’s private session. No wallet or custodial account.'}</p></>}
  {round.protocol&&<div className="live-toolbar"><button disabled={busy} onClick={syncLive}>Refresh protocol state</button>{now>=round.spec.observation_time&&now<round.spec.resolution_deadline&&['open','closed','pending'].includes(round.status)&&<button disabled={busy} onClick={()=>protocolAction('adjudicate')}>Request resolution</button>}{now>=round.spec.resolution_deadline&&['open','closed','pending'].includes(round.status)&&<button disabled={busy} onClick={()=>protocolAction('void')}>Void expired round</button>}<span role="status">{liveStatus}</span></div>}
  {(prediction||round.protocol)&&round.status==='resolved'&&<div className="result-block"><div><span>Observed opening weekend</span><strong>{money(round.evidence!.normalized_value)}</strong><p>Winning range: {rangeLabel(round.spec.ranges[round.winner!])}</p></div>{prediction&&<div className="result-points"><Target size={25}/><strong>{prediction.kind==='protocol'?score(prediction,round).points:score(prediction,round).practicePoints}</strong><span>{prediction.kind==='protocol'?'league points':'practice points'}</span><p>{prediction.range===round.winner?'Right on target.':'A miss. The next call is yours.'}{prediction.guess?' Your exact number earned '+score(prediction,round).closenessPoints+' closeness points.':''}</p></div>}</div>}
  {prediction&&round.status!=='resolved'&&<div className="notice" role="status">{round.status==='void'?'Round void. No score or accuracy change.':'Your prediction is saved. The result is pending; no points awarded.'}</div>}
  <Histogram round={round}/><Rules round={round}/>{prediction&&<><details className="disclosure"><summary>Your saved receipt <Plus size={18}/></summary><dl className="technical"><dt>Receipt</dt><dd><code>{prediction.id}</code></dd><dt>Submitted</dt><dd>{date(prediction.submittedAt)}</dd><dt>Status</dt><dd>Practice confirmed in the local application database. This is not a GenLayer transaction.</dd></dl></details>{round.status==='resolved'&&<EvidencePanel round={round}/>}</>}
  {round.protocol&&round.status==='resolved'&&<EvidencePanel round={round}/>}</section></div></>)}
  {data&&view==='predictions'&&<section className="interior"><h1>Your calls,<br/><span>on the record.</span></h1><p className="intro">The range you chose. The result it met. Every call stays visible.</p><div className="section-heading"><h2>My predictions</h2><span>{data.predictions.length} saved {data.predictions.length===1?'call':'calls'}</span></div>{data.predictions.length===0?<div className="empty"><Target size={35}/><h3>Your first call is waiting.</h3><p>Try a historical round to learn the ropes.</p><Link className="button primary" href="/rounds/barbie-practice">Play the Barbie round <ArrowRight size={17}/></Link></div>:data.predictions.map(p=>{const r=data.rounds.find(r=>r.id===p.roundId)!;const result=score(p,r);return <Link href={'/rounds/'+r.id+'/result'} className="prediction-row" key={p.id}><div><span className="tag">{r.spec.mode==='historical'?'Historical':'Synthetic'} practice</span><h3>{r.title}</h3><p>{rangeLabel(r.spec.ranges[p.range])}</p></div><div><strong>{r.status==='resolved'?(p.kind==='protocol'?result.points+' league pts':result.practicePoints+' practice pts'):r.status==='void'?'Void':'Pending'}</strong><p>{r.status==='resolved'?(result.correct?'Correct range':'Incorrect range'):'No accuracy change'}</p></div><ArrowUpRight size={20}/></Link>;})}<p className="notice">Practice never appears in the competitive leaderboard. Your session persists across reloads; clearing cookies creates a new guest.</p></section>}
  {data&&view==='league'&&<section className="interior"><h1>Good calls<br/><span>add up.</span></h1><p className="intro">A shared record, earned one opening weekend at a time.</p><div className="section-heading"><h2>The league</h2><span>100 points per correct finalized call</span></div>{data.leaderboard.length===0?<div className="empty"><Target size={36}/><h3>The leaderboard starts with proof.</h3><p>No competitive rounds have finalized yet. Historical practice and synthetic rehearsals are excluded.</p><Link className="button secondary" href="/create">Draft a competitive round <Plus size={17}/></Link></div>:<table><thead><tr><th>Forecaster</th><th>Points</th><th>Accuracy</th></tr></thead><tbody>{data.leaderboard.map((row,i)=><tr key={i}><td>{row.name}</td><td>{row.points}</td><td>{Math.round(row.correct/row.resolved*100)}%</td></tr>)}</tbody></table>}<div className="two-column"><div><h3>Points, without the stakes.</h3><p>Correct predictions earn 100 free league points. Incorrect predictions earn zero. Points have no monetary value.</p></div><div><h3>A record worth comparing.</h3><p>Only successful, finalized protocol entries and settled competitive rounds count. Pending and void rounds are excluded from accuracy.</p></div></div><NetworkProof proof={proof}/></section>}
  {data&&view==='pools'&&<MoviePoolDirectory/>}
  {data&&view==='pool-rehearsal'&&<PoolRehearsal connect={walletClient}/>}
  {data&&view==='creator'&&<Creator savedDraft={data.draft} proof={proof} onError={setError}/>}
  {data&&data.receipts.length>0&&view==='predictions'&&<section className="receipts"><h2>Protocol receipts</h2>{data.receipts.map(receipt=><div className="notice" key={receipt.hash}><strong>{receipt.state}</strong><p><code>{receipt.hash}</code></p><button className="button secondary" disabled={busy} onClick={()=>checkReceipt(receipt.hash)}>Refresh receipt</button></div>)}<p className="small">A finalized receipt can contain failed execution. Only finalized state contributes to the league.</p></section>}
  </main><footer className="footer"><Link className="brand" href="/"><Target size={21}/><span>BULLSEYE.</span></Link><p>Film instincts. Public evidence. Free league points.</p><span>Built with GenLayer</span></footer></>;
}
function Histogram({round}:{round:Round}){const total=round.histogram.reduce((a,b)=>a+b,0);return <section className="histogram"><div className="section-heading"><h2>How people called it</h2><span>{total} {total===1?'prediction':'predictions'}</span></div><div className="hist-bars">{round.spec.ranges.map((range,i)=><div key={i}><div className="bar-track"><div style={{height:total?Math.max(4,round.histogram[i]/total*100)+'%':'0%'}}/><span>{round.histogram[i]}</span></div><p>{rangeLabel(range)}</p></div>)}</div><p className="small">Participant predictions in this practice instance. These are not calibrated probabilities.</p></section>;}
function NetworkProof({proof}:{proof:Proof|null}){return <section className="network-proof"><div><span className="status-dot"/><h3>{proof?.record?.status==='resolved'?'A real GenLayer resolution.':'GenLayer development network'}</h3><p>{proof?.record?.status==='resolved'?'The historical demo has a saved finalized specification and adjudication. Browse the record separately from your local practice.':'Protocol verification is pending. Local practice remains playable.'}</p></div><details><summary>Inspect protocol proof <ArrowUpRight size={16}/></summary>{proof?.record?<div className="proof-content"><p>StudioNet is a development simulator. This saved record is not a production-chain settlement or competitive round.</p><p>Status: <strong>{proof.record.status}</strong></p><p>Contract: <code>{proof.contract}</code></p>{Object.entries(proof.transactions).map(([label,hash])=><p key={label}>{label}: <code>{hash}</code></p>)}{proof.record.evidence&&<><p>Observed: {money(proof.record.evidence.normalized_value)}</p><blockquote>{passageText(proof.record.evidence.extracted_passage)}</blockquote></>}<a href="/protocol-proof.json" target="_blank" rel="noreferrer">Open saved proof JSON <ExternalLink size={14}/></a></div>:<p>{proof?.reason??'No finalized record has been published yet.'}</p>}</details></section>;}
function Creator({savedDraft,proof,onError}:{savedDraft:string;proof:Proof|null;onError:(message:string)=>void}){
  const saved=(()=>{try{return JSON.parse(savedDraft) as {proposal?:string;title?:string;weekend?:string;source?:string};}catch{return {proposal:savedDraft};}})();
  const [proposal,setProposal]=useState(saved.proposal||'Forecast the domestic opening-weekend box-office revenue for the exact film and weekend in the attached specification, in United States and Canada, in integer USD dollars as reported by The Numbers. Use every attached frozen rule.');
  const [title,setTitle]=useState(saved.title??'');const [weekend,setWeekend]=useState(saved.weekend??'');const [source,setSource]=useState(saved.source??'https://www.the-numbers.com/movie/');const [state,setState]=useState('draft');const [errors,setErrors]=useState<string[]>([]);const [spec,setSpec]=useState<Specification|null>(null);const [hash,setHash]=useState('');
  async function validate(){onError('');setState('validating');try{await post({action:'draft',draft:JSON.stringify({proposal,title,weekend,source})});const start=Date.parse(weekend+'T00:00:00Z')/1000;const next=baseSpec('competitive',[start-3600,start+4*86400,start+10*86400],defaultRanges);const end=new Date((start+2*86400)*1000).toISOString().slice(0,10);next.event=title+', '+weekend+' to '+end;next.source_url=source;const found=validateSpec(next);if(start<=Date.now()/1000)found.push('Choose a future release weekend.');setErrors(found);setSpec(next);setState(found.length?'invalid':'preview');}catch(e){setState('failed');onError((e as Error).message);}}
  async function submit(){if(!spec||!proof?.contract)return;setState('submitting');onError('');try{
    const client=await walletClient();
    const tx=await client.writeContract({address:proof.contract as `0x${string}`,functionName:'propose',args:['round-'+crypto.randomUUID().slice(0,8),proposal,JSON.stringify(spec)],value:0n});
    setHash(tx);await livePost({action:'receipt',hash:tx});localStorage.setItem('bullseye_creator_receipt',JSON.stringify({hash:tx,state:'submitted',spec}));setState('submitted');
  }catch(e){setState('failed');onError((e as Error).message);}}
  return <section className="interior creator"><h1>A good question.<br/><span>A clear finish.</span></h1><p className="intro">Freeze the metric, source, ranges and deadlines before anyone makes a call.</p><div className="creator-layout"><form onSubmit={e=>{e.preventDefault();validate();}}><label>Film and release year<input required placeholder="Film Title (2026)" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Opening Friday (UTC)<input required type="date" value={weekend} onChange={e=>setWeekend(e.target.value)}/></label><label>The Numbers film URL<input required type="url" value={source} onChange={e=>setSource(e.target.value)}/></label><label>Question and settlement rule<textarea required rows={5} value={proposal} onChange={e=>setProposal(e.target.value)}/></label><button className="button primary" disabled={state==='validating'} type="submit">{state==='validating'?'Checking…':'Save draft & check rules'}<ArrowRight size={18}/></button></form><aside><h2>Define the finish line.</h2><p>Domestic opening-weekend revenue. US and Canada. Published integer USD dollars.</p><ul><li>Four ranges cover $0 to infinity.</li><li>Close before release Friday.</li><li>Observe on the following Tuesday.</li><li>Missing evidence stays pending, then voids ten days after Friday.</li><li>First successful consensus observation; later corrections ignored.</li></ul><p className="small">Creators use their own wallet. The current deployment only accepts proposals from its owner; there is no backend relay or operator custody.</p></aside></div>
  <div role="status" aria-live="polite">{errors.length>0&&<div className="error"><strong>These rules need a fix.</strong><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}{state==='preview'&&<div className="notice"><strong>Rule preview ready. GenLayer validation is still pending.</strong><p>Local checks passed. Validators must interpret your question and successfully finalize the specification before entries can open.</p><button className="button secondary" onClick={submit} disabled={!proof?.contract}><Wallet size={17}/> Submit with creator wallet</button></div>}{state==='submitting'&&<p className="notice">Waiting for your wallet to submit…</p>}{state==='submitted'&&<p className="notice">Submitted. This does not establish successful execution or finality. <code>{hash}</code></p>}</div>{spec&&<details className="disclosure"><summary>Canonical specification preview <Plus size={17}/></summary><pre>{JSON.stringify(spec,null,2)}</pre></details>}<NetworkProof proof={proof}/></section>;
}
