'use client';
import {useCallback,useEffect,useState} from 'react';
import type {GenLayerClient} from 'genlayer-js/types';
import {studionet} from 'genlayer-js/chains';
import {claimable,gen,parseStake,poolLabels,type Pool} from '@/lib/pools';
type Snapshot={contract:`0x${string}`;pools:Pool[];payoutVerified:boolean};
export default function PoolRehearsal({connect}:{connect:()=>Promise<GenLayerClient<typeof studionet>>}){
  const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[address,setAddress]=useState(''),[amount,setAmount]=useState('2'),[selection,setSelection]=useState<Record<string,number>>({}),[now,setNow]=useState(0),[receipt,setReceipt]=useState<{hash:string;state:string;action:string;transfers?:{hash:string;state:string;recipient:string}[]}|null>(null);
  const refresh=useCallback(async()=>{const response=await fetch('/api/pools',{cache:'no-store'});const value=await response.json();if(!response.ok)throw Error(value.error);setData(value);setNow(Math.floor(Date.now()/1000));},[]);
  useEffect(()=>{Promise.resolve().then(()=>refresh()).catch(e=>setError(e.message));Promise.resolve().then(()=>{const saved=localStorage.getItem('bullseye_pool_receipt');if(saved){try{setReceipt(JSON.parse(saved));}catch{localStorage.removeItem('bullseye_pool_receipt');}}});
    const provider=(window as unknown as {ethereum?:{request:(args:{method:string})=>Promise<string[]>;on?:(event:string,fn:(accounts:string[])=>void)=>void;removeListener?:(event:string,fn:(accounts:string[])=>void)=>void}}).ethereum;
    const changed=(accounts:string[])=>setAddress(accounts[0]?.toLowerCase()??'');provider?.request({method:'eth_accounts'}).then(changed).catch(()=>{});provider?.on?.('accountsChanged',changed);const connected=(e:Event)=>setAddress(String((e as CustomEvent).detail).toLowerCase());window.addEventListener('bullseye:wallet-connected',connected);
    const timer=setInterval(()=>setNow(Math.floor(Date.now()/1000)),1000);return()=>{clearInterval(timer);provider?.removeListener?.('accountsChanged',changed);window.removeEventListener('bullseye:wallet-connected',connected);};},[refresh]);
  async function check(){if(!receipt)return;setBusy(true);setError('');try{const response=await fetch('/api/pools?receipt='+receipt.hash,{cache:'no-store'});const result=await response.json();if(!response.ok)throw Error(result.error);const next={...receipt,state:result.state,transfers:result.transfers};setReceipt(next);localStorage.setItem('bullseye_pool_receipt',JSON.stringify(next));await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function submit(action:string,pool?:Pool){if(!data)return;setBusy(true);setError('');try{const value=action==='stake'?parseStake(amount):0n;const chosen=pool?selection[pool.id]:undefined;if(action==='stake'&&chosen===undefined)throw Error('Choose a range before staking.');const client=await connect();const hash=await client.writeContract({address:data.contract,functionName:action,args:pool?(action==='stake'?[pool.id,chosen!]:[pool.id]):[],value});const next={hash,state:'submitted',action};setReceipt(next);localStorage.setItem('bullseye_pool_receipt',JSON.stringify(next));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <section className="interior pools"><span className="tag synthetic">StudioNet rehearsal</span><h1>MAKE A POOL.<br/><span>TEST THE PAYOUT.</span></h1><p className="intro">Stake at least 2 GEN on a range. The winning range shares the whole pot in proportion to each wallet’s stake.</p><div className="notice"><strong>Simulated GEN. Known synthetic result.</strong><p>StudioNet balances are development funds. The invented film opens at $42,500,000, so the middle range wins. This rehearses deposits and payouts; it awards no league points. Barbie, Oppenheimer and Dune remain free historical practice.</p></div>
    {error&&<div className="error" role="alert">{error}</div>}
    <div className="pool-toolbar"><button className="button primary" disabled={busy||!data?.payoutVerified} onClick={()=>submit('start_demo')}>Start a two-minute pool</button><button className="button secondary" disabled={busy} onClick={()=>{setError('');refresh().catch(e=>setError(e.message));}}>Refresh pools</button></div>
    {!data&&!error&&<p role="status">Loading finalized StudioNet pools…</p>}{data&&!data.payoutVerified&&<p className="notice">Deposits are disabled until the deployed payout flow has been verified.</p>}
    {receipt&&<div className="notice" role="status"><strong>{receipt.action}: {receipt.state}</strong><p>Refresh the receipt after signing. A claim transaction requests a transfer; check your wallet balance after the transfer finishes.</p><code>{receipt.hash}</code>{receipt.transfers?.map(t=><p key={t.hash}>Follow-up: {t.state} to <code>{t.recipient}</code>. <code>{t.hash}</code></p>)}<p><button className="button secondary" disabled={busy} onClick={check}>Refresh receipt & pools</button></p></div>}
    {data?.pools.map(pool=>{const entry=pool.entries[address],payout=claimable(pool,address),open=pool.status==='open'&&now<pool.entry_deadline;return <article className="pool-card" key={pool.id}><div className="section-heading"><h2>{pool.title} / {pool.id}</h2><span>{pool.status.replaceAll('_',' ')}</span></div><p>{open?'Entries close in '+Math.max(0,pool.entry_deadline-now)+' seconds.':'Entries closed.'} Total staked: <strong>{gen(pool.total)} simulated GEN</strong></p><div className="pool-options">{poolLabels.map((label,index)=><button key={label} data-winning={pool.status==='resolved'&&pool.winner===index?'true':undefined} disabled={busy||!open||!!entry||!data.payoutVerified} aria-pressed={selection[pool.id]===index} onClick={()=>setSelection(s=>({...s,[pool.id]:index}))}><strong>{label}</strong><span>{gen(pool.pools[index])} GEN pooled</span>{index===1&&<small>Known rehearsal winner</small>}</button>)}</div>
      {open&&!entry&&<div className="pool-entry"><label>Simulated GEN stake<input type="text" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="button primary" disabled={busy||selection[pool.id]===undefined||!data.payoutVerified} onClick={()=>submit('stake',pool)}>Stake with wallet</button></div>}
      {entry&&<p>Your entry: {gen(entry.stake)} GEN on {poolLabels[entry.range]}. {pool.claims[address]?'Transfer requested: '+gen(pool.claims[address])+' GEN. Verify arrival in your wallet.':''}</p>}
      {pool.status==='open'&&now>=pool.observation_time&&now<pool.resolution_deadline&&<button className="button secondary" disabled={busy} onClick={()=>submit('resolve',pool)}>Finalize synthetic result</button>}
      {pool.status==='open'&&now>=pool.resolution_deadline&&<button className="button secondary" disabled={busy} onClick={()=>submit('void',pool)}>Void pool for refunds</button>}
      {BigInt(payout)>0n&&<button className="button primary" disabled={busy||!data.payoutVerified} onClick={()=>submit('claim',pool)}>Claim {gen(payout)} simulated GEN</button>}
      {pool.status==='resolved'&&entry&&payout==='0'&&!pool.claims[address]&&<p>Your range did not win. No payout is due.</p>}
      <details className="disclosure"><summary>Pool rules & finality</summary><p>One immutable entry per wallet. Minimum 2, maximum 100 simulated GEN. Entries close two minutes after creation; resolution opens three seconds later. If unresolved after ten minutes, anyone can void for refunds. An empty winning pool also refunds all stakes. Integer payouts distribute the entire pot, including rounding dust, in entry order. No fees are taken from the pot.</p><p>Resolution and voiding require a successful finalized callback before claims open. Payout transfers follow claim finalization. The claim record records a transfer request, not proof of arrival.</p><p>{pool.fixture}</p><code>{data.contract}</code></details>
    </article>;})}
    {data&&data.pools.length===0&&<p>No pools yet. Start one, choose a range and sign your stake.</p>}<p className="small"><a href="/pool-proof.json" target="_blank" rel="noreferrer">Inspect the saved deposit and payout proof</a></p>
  </section>;
}
